FROM debian:jessie

EXPOSE 80

RUN DEBIAN_FRONTEND=noninteractive ;\
    apt-get update && \
    apt-get install --assume-yes \
        cron \
        bzip2 \
        nginx \
        php-apc \
        php5-apcu \
        php5-curl \
        php5-fpm \
        php5-gd \
        php5-cli \
        php5-imagick \
        php5-gmp \
        php5-intl \
        php5-mcrypt \
        php5-pgsql \
        php5-cli \
        && rm -rf /var/lib/apt/lists/*


#
# php5-ldap \
# cron

# RUN DEBIAN_FRONTEND=noninteractive ;\
#     apt-get update && \
#     apt-get install --assume-yes \
#       libcurl4-openssl-dev \
#       libfreetype6-dev \
#       libicu-dev \
#       libjpeg-dev \
#       libmcrypt-dev \
#       libmemcached-dev \
#       libpng12-dev \
#       libpq-dev \
#       libxml2-dev \

## Check latest version: https://owncloud.org/install/#instructions-server
ENV OWNCLOUD_VERSION 8.2.0

# Compile NGINX with caching
#
RUN gpg --keyserver ha.pool.sks-keyservers.net --recv-keys E3036906AD9F30807351FAC32D5D5E97F6978A26

RUN chown -R www-data /var/www/

## Fixes: PHP is configured to populate raw post data. Since PHP 5.6 this will lead to PHP throwing notices for perfectly valid code. #19
RUN echo 'always_populate_raw_post_data = -1' | tee --append /etc/php5/cli/php.ini /etc/php5/fpm/php.ini

## Allow usage of `sudo -u www-data php /var/www/owncloud/occ` with APC. ## FIXME: Temporally: https://github.com/owncloud/core/issues/17329
RUN echo 'apc.enable_cli = 1' >> /etc/php5/cli/php.ini

## Fixed warning in admin panel getenv('PATH') == '' for ownCloud 8.1.
RUN echo 'env[PATH] = /usr/local/bin:/usr/bin:/bin' >> /etc/php5/fpm/pool.d/www.conf

COPY owncloud.conf /etc/nginx/sites-enabled/default
COPY start_owncloud.sh /root/start_owncloud.sh
COPY config.php /var/www/owncloud/config/config.php

ADD https://download.owncloud.org/community/owncloud-${OWNCLOUD_VERSION}.tar.bz2 /tmp/owncloud.tar.bz2
ADD https://download.owncloud.org/community/owncloud-${OWNCLOUD_VERSION}.tar.bz2.asc /tmp/owncloud.tar.bz2.asc

RUN gpg --verify /tmp/owncloud.tar.bz2.asc \
	&& tar -xjf /tmp/owncloud.tar.bz2 -C /var/www \
	&& rm /tmp/owncloud.tar.bz2 /tmp/owncloud.tar.bz2.asc

CMD /root/start_owncloud.sh
